version: "3.9"

services:
  api:
    build: .
    container_name: taxi-tip-api
    ports:
      - "8000:8000"
    environment:
      # Example environment variable for model path
      MODEL_PATH: /app/mlruns/877646091967902175/models/m-3db070fbef074c74aebda62aaba47650/artifacts
      MODEL_NAME: taxi-tip-regressor
      MODEL_VERSION: 1
    depends_on:
      - mlflow   # only needed if you enable the bonus MLflow service
    networks:
      - taxi-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    volumes:
      - ./mlruns:/mlruns
    networks:
      - taxi-net

networks:
  taxi-net:
    driver: bridge
